# The contents of this file should be added to the default that is installed at /etc/freetds/freetds.conf

[global]
    tds version = 7.4
    encryption = require
    trust server certificate = yes
    connect timeout = 5
    timeout = 30

[sqlserver]
    host = 127.0.0.1
    port = 1433
