[agent]
  interval = "1s"
  flush_interval = "5s"
  metric_batch_size = 1000
  metric_buffer_limit = 100000
  logfile = "/var/log/telegraf/telegraf.log"
  debug = false

###############################################################################
# TCP Scanner Input
###############################################################################

[[inputs.socket_listener]]
  # This should be updated to the correct IP address of scanner_1
  service_address = "tcp://0.0.0.0:7000"
  data_format = "value"
  data_type = "string"
  name_override = "scanner_1"

  [inputs.socket_listener.tags]
    source = "nedap"

[[inputs.socket_listener]]
  # This should be updated to the correct IP address of scanner_2
  service_address = "tcp://0.0.0.0:7001"
  data_format = "value"
  data_type = "string"
  name_override = "scanner_2"

  [inputs.socket_listener.tags]
    source = "nedap"

# To add another scanner - uncomment out the following 
#   any number can be added just by copying & pasting the commented sections
# [[inputs.socket_listener]]
#   # This should be updated to the correct IP address of scanner_3
#   service_address = "tcp://0.0.0.0:7002"
#   data_format = "value"
#   data_type = "string"
#   name_override = "scanner_3"

#   [inputs.socket_listener.tags]
#     source = "nedap"

###############################################################################
# Write raw scans to disk (JSON lines)
###############################################################################

[[outputs.http]]
  # The URL for the local python server
  url = "http://127.0.0.1:5000/ingest"
  method = "POST"

  data_format = "json"

  ## Persist the scans locally if the python server isn't running
  metric_batch_size = 1000
  metric_buffer_limit = 10000

  # Optional headers
  [outputs.http.headers]
    Content-Type = "application/json"