[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 100000
  flush_interval = "30s"
  flush_jitter = "5s"
  precision = "1s"
  logfile = "/var/log/telegraf/telegraf.log"
  debug = true

[[inputs.socket_listener]]
  service_address = "tcp://0.0.0.0:7000"
  data_format = "value"
  data_type = "string"
  [inputs.socket_listener.tags]
    source = "barcode_scanner"

[[processors.rename]]
  [[processors.rename.replace]]
    measurement = "socket_listener"
    dest = "barcode_scans"

[[outputs.kafka]]
  brokers = ["127.0.0.1:9092"]
  topic = "barcode_scans"
  data_format = "json"
